// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0
// source: data_transfer.proto

package rpm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataTransferPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsFine bool   `protobuf:"varint,1,opt,name=IsFine,proto3" json:"IsFine,omitempty"`
	Data   string `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	Action string `protobuf:"bytes,3,opt,name=Action,proto3" json:"Action,omitempty"`
}

func (x *DataTransferPayload) Reset() {
	*x = DataTransferPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_transfer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataTransferPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataTransferPayload) ProtoMessage() {}

func (x *DataTransferPayload) ProtoReflect() protoreflect.Message {
	mi := &file_data_transfer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataTransferPayload.ProtoReflect.Descriptor instead.
func (*DataTransferPayload) Descriptor() ([]byte, []int) {
	return file_data_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *DataTransferPayload) GetIsFine() bool {
	if x != nil {
		return x.IsFine
	}
	return false
}

func (x *DataTransferPayload) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *DataTransferPayload) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type DataTransferPaystub struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ack bool `protobuf:"varint,1,opt,name=Ack,proto3" json:"Ack,omitempty"`
}

func (x *DataTransferPaystub) Reset() {
	*x = DataTransferPaystub{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_transfer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataTransferPaystub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataTransferPaystub) ProtoMessage() {}

func (x *DataTransferPaystub) ProtoReflect() protoreflect.Message {
	mi := &file_data_transfer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataTransferPaystub.ProtoReflect.Descriptor instead.
func (*DataTransferPaystub) Descriptor() ([]byte, []int) {
	return file_data_transfer_proto_rawDescGZIP(), []int{1}
}

func (x *DataTransferPaystub) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

var File_data_transfer_proto protoreflect.FileDescriptor

var file_data_transfer_proto_rawDesc = []byte{
	0x0a, 0x13, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x59, 0x0a, 0x13,
	0x44, 0x61, 0x74, 0x61, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x73, 0x46, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x49, 0x73, 0x46, 0x69, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x16, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x27, 0x0a, 0x13, 0x44, 0x61, 0x74, 0x61, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x50, 0x61, 0x79, 0x73, 0x74, 0x75, 0x62, 0x12, 0x10,
	0x0a, 0x03, 0x41, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x41, 0x63, 0x6b,
	0x32, 0x5d, 0x0a, 0x13, 0x44, 0x61, 0x74, 0x61, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x50, 0x61, 0x79, 0x73, 0x74, 0x75, 0x62, 0x42,
	0x0c, 0x5a, 0x0a, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x70, 0x6d, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_data_transfer_proto_rawDescOnce sync.Once
	file_data_transfer_proto_rawDescData = file_data_transfer_proto_rawDesc
)

func file_data_transfer_proto_rawDescGZIP() []byte {
	file_data_transfer_proto_rawDescOnce.Do(func() {
		file_data_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(file_data_transfer_proto_rawDescData)
	})
	return file_data_transfer_proto_rawDescData
}

var file_data_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_data_transfer_proto_goTypes = []interface{}{
	(*DataTransferPayload)(nil), // 0: proto.DataTransferPayload
	(*DataTransferPaystub)(nil), // 1: proto.DataTransferPaystub
}
var file_data_transfer_proto_depIdxs = []int32{
	0, // 0: proto.DataTransferService.TransferData:input_type -> proto.DataTransferPayload
	1, // 1: proto.DataTransferService.TransferData:output_type -> proto.DataTransferPaystub
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_data_transfer_proto_init() }
func file_data_transfer_proto_init() {
	if File_data_transfer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_data_transfer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataTransferPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_transfer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataTransferPaystub); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_data_transfer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_transfer_proto_goTypes,
		DependencyIndexes: file_data_transfer_proto_depIdxs,
		MessageInfos:      file_data_transfer_proto_msgTypes,
	}.Build()
	File_data_transfer_proto = out.File
	file_data_transfer_proto_rawDesc = nil
	file_data_transfer_proto_goTypes = nil
	file_data_transfer_proto_depIdxs = nil
}
